// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/rocket/todolist/proto/user_login.proto

package com.rocket.todolist.protobuf;

public final class UserLogin {
  private UserLogin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserInfoRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.rocket.todolist.protobuf.UserInfoRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    long getUserId();
  }
  /**
   * Protobuf type {@code com.rocket.todolist.protobuf.UserInfoRequest}
   */
  public static final class UserInfoRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.rocket.todolist.protobuf.UserInfoRequest)
      UserInfoRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserInfoRequest.newBuilder() to construct.
    private UserInfoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserInfoRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserInfoRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserInfoRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rocket.todolist.protobuf.UserLogin.internal_static_com_rocket_todolist_protobuf_UserInfoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rocket.todolist.protobuf.UserLogin.internal_static_com_rocket_todolist_protobuf_UserInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rocket.todolist.protobuf.UserLogin.UserInfoRequest.class, com.rocket.todolist.protobuf.UserLogin.UserInfoRequest.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.rocket.todolist.protobuf.UserLogin.UserInfoRequest)) {
        return super.equals(obj);
      }
      com.rocket.todolist.protobuf.UserLogin.UserInfoRequest other = (com.rocket.todolist.protobuf.UserLogin.UserInfoRequest) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.rocket.todolist.protobuf.UserLogin.UserInfoRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.rocket.todolist.protobuf.UserLogin.UserInfoRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.rocket.todolist.protobuf.UserInfoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.rocket.todolist.protobuf.UserInfoRequest)
        com.rocket.todolist.protobuf.UserLogin.UserInfoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rocket.todolist.protobuf.UserLogin.internal_static_com_rocket_todolist_protobuf_UserInfoRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rocket.todolist.protobuf.UserLogin.internal_static_com_rocket_todolist_protobuf_UserInfoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rocket.todolist.protobuf.UserLogin.UserInfoRequest.class, com.rocket.todolist.protobuf.UserLogin.UserInfoRequest.Builder.class);
      }

      // Construct using com.rocket.todolist.protobuf.UserLogin.UserInfoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rocket.todolist.protobuf.UserLogin.internal_static_com_rocket_todolist_protobuf_UserInfoRequest_descriptor;
      }

      @java.lang.Override
      public com.rocket.todolist.protobuf.UserLogin.UserInfoRequest getDefaultInstanceForType() {
        return com.rocket.todolist.protobuf.UserLogin.UserInfoRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.rocket.todolist.protobuf.UserLogin.UserInfoRequest build() {
        com.rocket.todolist.protobuf.UserLogin.UserInfoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.rocket.todolist.protobuf.UserLogin.UserInfoRequest buildPartial() {
        com.rocket.todolist.protobuf.UserLogin.UserInfoRequest result = new com.rocket.todolist.protobuf.UserLogin.UserInfoRequest(this);
        result.userId_ = userId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rocket.todolist.protobuf.UserLogin.UserInfoRequest) {
          return mergeFrom((com.rocket.todolist.protobuf.UserLogin.UserInfoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rocket.todolist.protobuf.UserLogin.UserInfoRequest other) {
        if (other == com.rocket.todolist.protobuf.UserLogin.UserInfoRequest.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rocket.todolist.protobuf.UserLogin.UserInfoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rocket.todolist.protobuf.UserLogin.UserInfoRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 1;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.rocket.todolist.protobuf.UserInfoRequest)
    }

    // @@protoc_insertion_point(class_scope:com.rocket.todolist.protobuf.UserInfoRequest)
    private static final com.rocket.todolist.protobuf.UserLogin.UserInfoRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.rocket.todolist.protobuf.UserLogin.UserInfoRequest();
    }

    public static com.rocket.todolist.protobuf.UserLogin.UserInfoRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserInfoRequest>
        PARSER = new com.google.protobuf.AbstractParser<UserInfoRequest>() {
      @java.lang.Override
      public UserInfoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserInfoRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserInfoRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfoRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.rocket.todolist.protobuf.UserLogin.UserInfoRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserInfoResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.rocket.todolist.protobuf.UserInfoResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 userType = 1;</code>
     * @return The userType.
     */
    int getUserType();

    /**
     * <code>string mobile = 2;</code>
     * @return The mobile.
     */
    java.lang.String getMobile();
    /**
     * <code>string mobile = 2;</code>
     * @return The bytes for mobile.
     */
    com.google.protobuf.ByteString
        getMobileBytes();
  }
  /**
   * Protobuf type {@code com.rocket.todolist.protobuf.UserInfoResponse}
   */
  public static final class UserInfoResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.rocket.todolist.protobuf.UserInfoResponse)
      UserInfoResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserInfoResponse.newBuilder() to construct.
    private UserInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserInfoResponse() {
      mobile_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserInfoResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserInfoResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userType_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              mobile_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rocket.todolist.protobuf.UserLogin.internal_static_com_rocket_todolist_protobuf_UserInfoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rocket.todolist.protobuf.UserLogin.internal_static_com_rocket_todolist_protobuf_UserInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rocket.todolist.protobuf.UserLogin.UserInfoResponse.class, com.rocket.todolist.protobuf.UserLogin.UserInfoResponse.Builder.class);
    }

    public static final int USERTYPE_FIELD_NUMBER = 1;
    private int userType_;
    /**
     * <code>int32 userType = 1;</code>
     * @return The userType.
     */
    @java.lang.Override
    public int getUserType() {
      return userType_;
    }

    public static final int MOBILE_FIELD_NUMBER = 2;
    private volatile java.lang.Object mobile_;
    /**
     * <code>string mobile = 2;</code>
     * @return The mobile.
     */
    @java.lang.Override
    public java.lang.String getMobile() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mobile_ = s;
        return s;
      }
    }
    /**
     * <code>string mobile = 2;</code>
     * @return The bytes for mobile.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMobileBytes() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userType_ != 0) {
        output.writeInt32(1, userType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mobile_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mobile_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mobile_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mobile_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.rocket.todolist.protobuf.UserLogin.UserInfoResponse)) {
        return super.equals(obj);
      }
      com.rocket.todolist.protobuf.UserLogin.UserInfoResponse other = (com.rocket.todolist.protobuf.UserLogin.UserInfoResponse) obj;

      if (getUserType()
          != other.getUserType()) return false;
      if (!getMobile()
          .equals(other.getMobile())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getUserType();
      hash = (37 * hash) + MOBILE_FIELD_NUMBER;
      hash = (53 * hash) + getMobile().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.rocket.todolist.protobuf.UserLogin.UserInfoResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rocket.todolist.protobuf.UserLogin.UserInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.rocket.todolist.protobuf.UserLogin.UserInfoResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.rocket.todolist.protobuf.UserInfoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.rocket.todolist.protobuf.UserInfoResponse)
        com.rocket.todolist.protobuf.UserLogin.UserInfoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rocket.todolist.protobuf.UserLogin.internal_static_com_rocket_todolist_protobuf_UserInfoResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rocket.todolist.protobuf.UserLogin.internal_static_com_rocket_todolist_protobuf_UserInfoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rocket.todolist.protobuf.UserLogin.UserInfoResponse.class, com.rocket.todolist.protobuf.UserLogin.UserInfoResponse.Builder.class);
      }

      // Construct using com.rocket.todolist.protobuf.UserLogin.UserInfoResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userType_ = 0;

        mobile_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rocket.todolist.protobuf.UserLogin.internal_static_com_rocket_todolist_protobuf_UserInfoResponse_descriptor;
      }

      @java.lang.Override
      public com.rocket.todolist.protobuf.UserLogin.UserInfoResponse getDefaultInstanceForType() {
        return com.rocket.todolist.protobuf.UserLogin.UserInfoResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.rocket.todolist.protobuf.UserLogin.UserInfoResponse build() {
        com.rocket.todolist.protobuf.UserLogin.UserInfoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.rocket.todolist.protobuf.UserLogin.UserInfoResponse buildPartial() {
        com.rocket.todolist.protobuf.UserLogin.UserInfoResponse result = new com.rocket.todolist.protobuf.UserLogin.UserInfoResponse(this);
        result.userType_ = userType_;
        result.mobile_ = mobile_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rocket.todolist.protobuf.UserLogin.UserInfoResponse) {
          return mergeFrom((com.rocket.todolist.protobuf.UserLogin.UserInfoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rocket.todolist.protobuf.UserLogin.UserInfoResponse other) {
        if (other == com.rocket.todolist.protobuf.UserLogin.UserInfoResponse.getDefaultInstance()) return this;
        if (other.getUserType() != 0) {
          setUserType(other.getUserType());
        }
        if (!other.getMobile().isEmpty()) {
          mobile_ = other.mobile_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rocket.todolist.protobuf.UserLogin.UserInfoResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rocket.todolist.protobuf.UserLogin.UserInfoResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userType_ ;
      /**
       * <code>int32 userType = 1;</code>
       * @return The userType.
       */
      @java.lang.Override
      public int getUserType() {
        return userType_;
      }
      /**
       * <code>int32 userType = 1;</code>
       * @param value The userType to set.
       * @return This builder for chaining.
       */
      public Builder setUserType(int value) {
        
        userType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserType() {
        
        userType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object mobile_ = "";
      /**
       * <code>string mobile = 2;</code>
       * @return The mobile.
       */
      public java.lang.String getMobile() {
        java.lang.Object ref = mobile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mobile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mobile = 2;</code>
       * @return The bytes for mobile.
       */
      public com.google.protobuf.ByteString
          getMobileBytes() {
        java.lang.Object ref = mobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mobile = 2;</code>
       * @param value The mobile to set.
       * @return This builder for chaining.
       */
      public Builder setMobile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mobile = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMobile() {
        
        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      /**
       * <code>string mobile = 2;</code>
       * @param value The bytes for mobile to set.
       * @return This builder for chaining.
       */
      public Builder setMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mobile_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.rocket.todolist.protobuf.UserInfoResponse)
    }

    // @@protoc_insertion_point(class_scope:com.rocket.todolist.protobuf.UserInfoResponse)
    private static final com.rocket.todolist.protobuf.UserLogin.UserInfoResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.rocket.todolist.protobuf.UserLogin.UserInfoResponse();
    }

    public static com.rocket.todolist.protobuf.UserLogin.UserInfoResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserInfoResponse>
        PARSER = new com.google.protobuf.AbstractParser<UserInfoResponse>() {
      @java.lang.Override
      public UserInfoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserInfoResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserInfoResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfoResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.rocket.todolist.protobuf.UserLogin.UserInfoResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rocket_todolist_protobuf_UserInfoRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rocket_todolist_protobuf_UserInfoRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rocket_todolist_protobuf_UserInfoResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rocket_todolist_protobuf_UserInfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*com/rocket/todolist/proto/user_login.p" +
      "roto\022\034com.rocket.todolist.protobuf\"!\n\017Us" +
      "erInfoRequest\022\016\n\006userId\030\001 \001(\003\"4\n\020UserInf" +
      "oResponse\022\020\n\010userType\030\001 \001(\005\022\016\n\006mobile\030\002 " +
      "\001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_rocket_todolist_protobuf_UserInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_rocket_todolist_protobuf_UserInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rocket_todolist_protobuf_UserInfoRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_com_rocket_todolist_protobuf_UserInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_rocket_todolist_protobuf_UserInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rocket_todolist_protobuf_UserInfoResponse_descriptor,
        new java.lang.String[] { "UserType", "Mobile", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
